---
# tasks file for wordpress
- name: Baixa a versão mais recente do WordPress
  get_url:
    url: "https://wordpress.org/latest.tar.gz"
    dest: "/tmp/wordpress.tar.gz"
    validate_certs: yes


- name: Descompacta o arquivo do WordPress
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/var/www/"
    remote_src: yes

- name: Ajusta permissões e proprietário da pasta WordPress
  file:
    path: "{{ wp_install_dir }}"
    owner: "{{ wp_owner_user }}"
    group: "{{ wp_owner_group }}"
    mode: "0755"
    recurse: yes

- name: Atualiza a configuração do VirtualHost padrão do Apache
  lineinfile:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    regexp: "(.)+DocumentRoot /var/www/html"
    line: "DocumentRoot {{ wp_install_dir }}"
  notify:
    - reinicia apache

- name: Copia o arquivo wp-config-sample.php para wp-config.php
  command: "cp {{ wp_install_dir }}/wp-config-sample.php {{ wp_install_dir }}/wp-config.php"
  args:
    creates: "{{ wp_install_dir }}/wp-config.php"

- name: Configura os parâmetros de acesso ao banco de dados no wp-config.php
  lineinfile:
    path: "{{ wp_install_dir }}/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backup: yes
  loop:
    - { regexp: "database_name_here", line: "define('DB_NAME', '{{ wp_mysql_db }}');" }
    - { regexp: "username_here", line: "define('DB_USER', '{{ wp_mysql_user }}');" }
    - { regexp: "password_here", line: "define('DB_PASSWORD', '{{ wp_mysql_password }}');" }
    - { regexp: "DISALLOW_FILE_EDIT", line: "define('DISALLOW_FILE_EDIT', true);" }

- name: Cria a pasta do plugin LSCIT Cyber Trilha Auth Gate
  file:
    path: "{{ wp_install_dir }}/wp-content/plugins/lscit-trilha-auth-gate"
    state: directory
    owner: "{{ wp_owner_user }}"
    group: "{{ wp_owner_group }}"
    mode: "0755"

- name: Copia os arquivos do plugin LSCIT Cyber para a pasta do WordPress
  copy:
    src: "{{ item }}"
    dest: "{{ wp_install_dir }}/wp-content/plugins/lscit-trilha-auth-gate/"
    owner: "{{ wp_owner_user }}"
    group: "{{ wp_owner_group }}"
    mode: "0644"
  loop:
    - "{{ playbook_dir }}/lscit-trilha-auth-gate.php"
    - "{{ playbook_dir }}/lscit-cyber-theme.css"