---
# tasks file for mysql
- name: Cria o banco de dados para o WordPress
  mysql_db:
    name: "{{ wp_mysql_db }}"
    state: present

- name: Cria um usuário de banco para o WordPress
  mysql_user:
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_password }}"
    priv: "{{ wp_mysql_db }}.*:ALL"
    state: present