---
# tasks file for server
- name: Atualiza o cache apt do servidor
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalação dos pacotes base do servidor Web e Banco
  apt:
    name:
      - apache2
      - mysql-server
      - php-mysql
      - php
      - libapache2-mod-php
      - python3-pymysql
    state: present
