---
# tasks file for server
- name: Atualiza o cache apt do servidor
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Instalação dos pacotes base do servidor Web e Banco
  apt:
    name:
      - apache2
      - mysql-server
      - php-mysql
      - php
      - libapache2-mod-php
      - python3-pymysql
    state: present

- name: Ativa o módulo mod_rewrite do Apache para permalinks amigáveis
  apache2_module:
    name: rewrite
    state: present
  notify:
    - reinicia apache

- name: Garante que os serviços Web e Banco estejam iniciados
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - apache2
    - mysql

